### ISSUE TITLE
TypeError: no implicit conversion of Array into String

### ISSUE THREAD

**Issue by forthrin** [ruby/webrick#117]
Why is this happening, and what is the proper fix?

```
get '/' do
  content_type 'text/plain'
  request.env.each do |k, v|
    puts "#{k}: #{v}"
  end
end
```

```
TypeError: no implicit conversion of Array into String in ./rack-2.2.7/lib/rack/handler/webrick.rb:120
              part = "#{part.join(': ')}\n" if part.is_a?(Array) # Hack
              res.body << part
```

Notices:

1. An old version of rack is used (2.2.7 as opposed to the current 3.0.8)
2. Some users seem to be switching to Puma. Is WEBrick outdated?

**Comment by ioquatix** [comment]
Do you need to return a response or something?

**Comment by ioquatix** [comment]
What framework is

```
get '/' do
  content_type 'text/plain'
  request.env.each do |k, v|
    puts "#{k}: #{v}"
  end
end
```

**Comment by jeremyevans** [comment]
Looks like Sinatra.  The issue is the `get` block is not returning one of Sinatra's expected return values.  See the Return Values section of https://sinatrarb.com/intro.html .  This appears to be a bug in the app, not in Webrick.
