### ISSUE TITLE
Shutdown after no request for x seconds

### ISSUE THREAD

**Issue by tscheingeld32** [ruby/webrick#39]
I'm trying to figure out how to shutdown a WEBrick server after some given number of seconds of inactivity. I'm writing a microservice that is in intended to only last for a short amount of time, usually a few seconds. Ideally the client process should send a shutdown command when it's done with the service, but I want a backup in which the microservice shuts down if no requests are received after, say 2 seconds.

Here's what I've tried that doesn't work.

    server = WEBrick::HTTPServer.new(:Port => 8000)
    WEBrick::Utils::TimeoutHandler.register(2, Timeout::Error)
    server.start

I thought that would simply exit the process after 2 seconds. Here's what actually happens:

    [2020-01-19 15:41:10] INFO  WEBrick 1.4.2
    [2020-01-19 15:41:10] INFO  ruby 2.5.1 (2018-03-29) [x86_64-linux-gnu]
    [2020-01-19 15:41:10] INFO  WEBrick::HTTPServer#start: pid=16622 port=8000
    [2020-01-19 15:41:12] ERROR Timeout::Error: execution timeout
        /usr/lib/ruby/2.5.0/webrick/server.rb:170:in `select'

And then the process keeps running. I have to ctrl-c to end it.

What's the correct way to shut down a server and end the process after a timeout?

**Comment by jeremyevans** [comment]
You probably want to do something like:

```ruby
Thread.new{sleep(2); exit}
```

Do you think that will work for you?

**Comment by jeremyevans** [comment]
Closing due to lack of response.
