### ISSUE TITLE
webrick missing as requirement?

### ISSUE THREAD

**Issue by Uzlopak** [ruby/webrick#93]
I tried to test the theme locally, but it threw an error. It could not require webrick. I manually added the gem to the Gemfile, installed again and then it worked. 

I am not a ruby dev, so I am wondering if this is the correct way to do it?

**Comment by jeremyevans** [comment]
Yes, that sounds correct.

**Comment by Uzlopak** [comment]
@jeremyevans 

I thought I created this issue in the mimima repo. I apologize.
